// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: 'category',
      label: "教程",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial",
        }
      ]
    },
    {
      type: 'category',
      label: "Alconna",
      items: [
        {
          type: "autogenerated",
          dirName: "alconna",
        }
      ]
    },
    {
      type: 'category',
      label: "NEPattern",
      items: [
        {
          type: "autogenerated",
          dirName: "nepattern",
        }
      ]
    }
    // {
    //   type: 'category',
    //   label: 'Letoderea',
    //   items:[
    //     'letoderea/tutorial',
    //     'letoderea/fast-start',
    //     {
    //       type: 'category',
    //       label: "基础",
    //       items: [
    //         'event',
    //         'auxiliary',
    //       ].map(value => `letoderea/basic/${value}`)
    //     },
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'Edoves',
    //   items:[
    //     'edoves/tutorial',
    //     {
    //       type: 'category',
    //       label: "入门",
    //       items: [
    //         'hello-world',
    //         'explain',
    //       ].map(value => `edoves/fast-start/${value}`)
    //     },
    //     {
    //       type: 'category',
    //       label: "基础",
    //       items: [
    //         'interact',
    //         'scene',
    //       ].map(value => `edoves/edoves-basic/${value}`)
    //     },
    //   ]
    // },
  ],
};

module.exports = sidebars;
